import Head from 'next/head';
import Link from 'next/link';

//Image
import Image from 'next/image';
import developer from '../public/imgs/profile/developer-pic1.png';

//components
import Layout from '@/components/Layout';
import Socials from '@/components/Socials';

//framer motion
import { motion } from "framer-motion";

//variants
import { fadeIn } from "@/utils/variants";

export default function Home() {
	return (
		<>
			<Head>
				<title>Dmzdev • Home</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="flex items-center w-full min-h-screen text-dark">
				<Layout className="pt-0">
					<div className="flex items-center justify-between w-full">
						<motion.div
							variants={fadeIn('up', 0.6)}
							initial="hidden"
							animate="show"
							exit="hidden"
							transition={{ duration: 1, ease: 'easeInOut' }}
							className="w-1/2"
						>
							<Image src={developer} alt="dmz dev" className="w-full h-auto" />
						</motion.div>
						<div className="flex items-center self-center w-1/2">
							<div className="flex flex-col items-center w-full mx-auto py-2 text-left">
								<motion.h1
									variants={fadeIn('down', 0.2)}
									initial="hidden"
									animate="show"
									exit="hidden"
									className="inline-block w-full text-dark font-bold capitalize text-4xl"
								>
									Turning Ideas into Digital Experiences With{' '}
									<span className="text-tertiary">Code And Design.</span>
								</motion.h1>
								<motion.p
									variants={fadeIn('down', 0.4)}
									initial="hidden"
									animate="show"
									exit="hidden"
									className="my-6 text-base font-medium"
								>
									Welcome to my web developer portfolio! My passion is
									transforming innovative ideas into web applications. I invite
									you to explore my projects, where I showcase my skills in
									Javascript and web development.
								</motion.p>
								<Socials />
							</div>
						</div>
					</div>
				</Layout>
			</main>
		</>
	);
}
